import type { Instrument } from "./types";
export const universe: Instrument[] = [
  { symbol: "^GSPC", name: "S&P 500", region: "Índice", sector: "EE. UU." },
  {
    symbol: "^STOXX50E",
    name: "EURO STOXX 50",
    region: "Índice",
    sector: "Europa",
  },
  { symbol: "^IBEX", name: "IBEX 35", region: "Índice", sector: "España" },
  { symbol: "^VIX", name: "VIX", region: "Índice", sector: "Volatilidad" },
  {
    symbol: "MSFT",
    name: "Microsoft",
    region: "EE. UU.",
    sector: "Tecnología",
  },
  {
    symbol: "NVDA",
    name: "NVIDIA",
    region: "EE. UU.",
    sector: "Semiconductores",
  },
  { symbol: "AAPL", name: "Apple", region: "EE. UU.", sector: "Tecnología" },
  {
    symbol: "GOOGL",
    name: "Alphabet",
    region: "EE. UU.",
    sector: "Comunicación",
  },
  { symbol: "AMZN", name: "Amazon", region: "EE. UU.", sector: "Consumo" },
  { symbol: "META", name: "Meta", region: "EE. UU.", sector: "Comunicación" },
  {
    symbol: "BRK-B",
    name: "Berkshire Hathaway",
    region: "EE. UU.",
    sector: "Finanzas",
  },
  { symbol: "JPM", name: "JPMorgan", region: "EE. UU.", sector: "Finanzas" },
  { symbol: "LLY", name: "Eli Lilly", region: "EE. UU.", sector: "Salud" },
  { symbol: "XOM", name: "Exxon Mobil", region: "EE. UU.", sector: "Energía" },
  { symbol: "PLTR", name: "Palantir", region: "EE. UU.", sector: "Tecnología" },
  { symbol: "TSLA", name: "Tesla", region: "EE. UU.", sector: "Automoción" },
  {
    symbol: "ASML.AS",
    name: "ASML",
    region: "Europa",
    sector: "Semiconductores",
  },
  { symbol: "SAP.DE", name: "SAP", region: "Europa", sector: "Tecnología" },
  { symbol: "SIE.DE", name: "Siemens", region: "Europa", sector: "Industria" },
  {
    symbol: "AIR.PA",
    name: "Airbus",
    region: "Europa",
    sector: "Aeroespacial",
  },
  { symbol: "MC.PA", name: "LVMH", region: "Europa", sector: "Consumo" },
  {
    symbol: "NOVO-B.CO",
    name: "Novo Nordisk",
    region: "Europa",
    sector: "Salud",
  },
  { symbol: "SAN.MC", name: "Santander", region: "Europa", sector: "Finanzas" },
  { symbol: "IBE.MC", name: "Iberdrola", region: "Europa", sector: "Energía" },
  { symbol: "ITX.MC", name: "Inditex", region: "Europa", sector: "Consumo" },
  {
    symbol: "RHM.DE",
    name: "Rheinmetall",
    region: "Europa",
    sector: "Defensa",
  },
];
